export const AUTO_TAG_PREFIX = "自动生成/";

export function normalizeTag(tag: string): string {
  return String(tag || "").replace(/\\/g, "/").trim().replace(/^\/+|\/+$/g, "");
}

export function isAutoGeneratedTag(tag: string): boolean {
  return normalizeTag(tag).startsWith(AUTO_TAG_PREFIX);
}

export function isAutoTagForNovel(tag: string, novelId: string): boolean {
  const nid = String(novelId || "").trim();
  if (!nid) return false;
  return normalizeTag(tag).startsWith(`${AUTO_TAG_PREFIX}${nid}/`);
}

export function scopeTagsForNovel(allTags: string[], novelId: string): string[] {
  return (allTags || []).filter((tag) => {
    if (!isAutoGeneratedTag(tag)) return true;
    return isAutoTagForNovel(tag, novelId);
  });
}

